version: '3.8'

services:
  wows-renderer:
    container_name: wows-renderer-service
    image: wows-renderer-service:latest
    build:
      context: .
      args:
        CACHEBUST: ${CACHEBUST:-1}
    restart: unless-stopped
    ports:
      - "8089:8000"
    environment:
      - TZ=Asia/Shanghai
      - MAX_CONCURRENT_RENDERS=2
    # 如果需要限制资源，可以取消注释以下内容
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
